project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"
    - "!CLAUDE.md"

website:
  title: "HAL-QuIC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: roadmap.qmd
        text: Project Roadmap
      - href: model.qmd
        text: Modeling
      - href: explorer.qmd
        text: Explorer
      - href: experiments.qmd
        text: Experiments
    right:
      - href: https://gagerowden.com
        text: "GageRowden.com"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    toc-depth: 3
    fig-align: center
    mermaid:
      theme: dark

execute:
  warning: false
  message: false